module5-task1
htmlacademy-javascript/25328-keksobooking-21 pull request #11
Opened 2020-10-07 16:39 UTC by Sainthedgehog1

2020-10-07 22:07 UTC, yulllll requested changes

2020-10-07 22:07 UTC, yulllll commented on js/form.js
> +  let minTitleLength = inputTitle.minLength;
не let, а const везде, где переменная не переопределяется

2020-10-07 22:07 UTC, yulllll commented on js/form.js
> +      if (capacityValidValues[rooms].indexOf(option.value) === -1) {
здесь мы можем упростить по критерию до 
````
option.disabled = capacityValidValues[rooms].indexOf(option.value) === -1;

2020-10-07 22:07 UTC, yulllll commented on js/form.js
> +    adForm,
здесь тоже поле объекта содержим в своем имени название объекта

2020-10-07 22:07 UTC, yulllll commented on js/map.js
> +    map,
надо подумать над именами модулей и полей
https://up.htmlacademy.ru/javascript/21/criteries#d3

2020-10-07 22:07 UTC, yulllll commented on js/pin.js
> +    getPins,
https://up.htmlacademy.ru/javascript/21/criteries#d3

2020-10-07 22:07 UTC, yulllll commented on js/util.js
> +  const isEscEvent = (evt, action) => {
замени action на callback - это общепринятое название таких функций, которые передаются в аргументы

2020-10-08 06:54 UTC, Sainthedgehog1 commented on js/card.js
> +    const renderPhotos = (popupPhotos, photosCard) => {
Я так понял что это уже 2 уровень js

2020-10-08 06:55 UTC, Sainthedgehog1 commented on js/card.js
> +    const {avatar} = data.author;
посмотрел

2020-10-08 07:06 UTC, Sainthedgehog1 commented on js/form.js
> +      if (capacityValidValues[rooms].indexOf(option.value) === -1) {
не понял

2020-10-08 08:08 UTC, merged