module5-task2
htmlacademy-javascript/25328-keksobooking-21 pull request #12
Opened 2020-10-08 13:26 UTC by Sainthedgehog1

2020-10-09 21:11 UTC, yulllll requested changes

2020-10-09 21:11 UTC, yulllll commented on js/main.js
> +    mainPin.addEventListener(`mousedown`, onMainPinMouseMove);
у тебя выше активация карты включается по click, а должна происходить по mousedown (т.е. внутри этого обработчика)

2020-10-09 21:11 UTC, yulllll commented on js/move.js
> +    onMainPinMouseMove,
опять слово move внутри модуля move - переименуй модуль, например, на maffinHandlers

2020-10-10 07:27 UTC, Sainthedgehog1 commented on js/main.js
> +    mainPin.addEventListener(`mousedown`, onMainPinMouseMove);
Я чет не понял что не так, по click (нажал кнопку мышки и отпустил) я активируют карту, а по mousedown я нажал и держиу нажатым эту клавишу

2020-10-10 07:49 UTC, Sainthedgehog1 commented on js/main.js
> +    mainPin.addEventListener(`mousedown`, onMainPinMouseMove);
В чем прикол того, что я нажму кнопку и буду ее держать (активируется страница), но что бы мне двигать мафин все все равно прийдется отпустить нажатую кнопку и заново ее зажать, что бы двигать

2020-10-11 00:04 UTC, merged