Module3 task2
htmlacademy-javascript/25328-keksobooking-21 pull request #7
Opened 2020-09-30 11:39 UTC by Sainthedgehog1

2020-09-30 14:14 UTC, yulllll requested changes

2020-09-30 14:14 UTC, yulllll commented on js/main.js
> +  for (let j = cardFeatures.length; j--;) {
1) это неправильный цикл
2) замени на forEach

2020-09-30 14:14 UTC, yulllll commented on js/main.js
> +  for (let j = cardFeatures.length; j--;) {
быстрее всего очищать содержимое элемента через 
cardFeaturesContainer.innerHTML = '';
и не нужен будет вообще проход по циклу

2020-09-30 14:14 UTC, yulllll commented on js/main.js
> +    const cardPhotos = array.querySelector(`.popup__photos`);
array - имя типа, переименуй и опиши, что за объект(ы) внутри этой переменной

2020-09-30 14:14 UTC, yulllll commented on js/main.js
> +    while (cardPhotos.firstChild) {
замени проход по циклу на эффективную очистку из комментария выше

2020-09-30 14:14 UTC, yulllll commented on js/main.js
> +  const generateFeatures = (featuresCard) => {
старайся не объявлять функцию внутри функции - усложняет читаемость кода

функции должны быть внутри модулей - посмотри критерий про IIFE и поправь

2020-09-30 14:14 UTC, yulllll commented on js/main.js
> +    case (`flat`):
у тебя здесь строки - это магические значения
создай вверху файла (модуля) enum c этими строками, а здесь воспользуйся уже указанием на поля перечисления

2020-09-30 17:28 UTC, Sainthedgehog1 commented on js/main.js
> +  const generateFeatures = (featuresCard) => {
не понял

2020-09-30 17:28 UTC, Sainthedgehog1 commented on js/main.js
> +    case (`flat`):
не понял

2020-10-01 08:20 UTC, yulllll commented on js/main.js
> +    case (`flat`):
посмотри описание критерия https://up.htmlacademy.ru/javascript/21/criteries#b8
например, объяви вверху файла
const Housing = {
FLAT: 'flat',
BUNGALO: 'bungalo'
}

в switch используй уже ссылку на значение 
case Housing.FLAT:

2020-10-02 12:55 UTC, yulllll approved these changes

2020-10-02 12:55 UTC, merged