Module4 task1
htmlacademy-javascript/25328-keksobooking-21 pull request #9
Opened 2020-10-03 16:04 UTC by Sainthedgehog1

2020-10-04 15:53 UTC, yulllll requested changes

2020-10-04 15:53 UTC, yulllll commented on index.html
> +      <form class="ad-form ad-form--disabled" action="https://javascript.pages.academy/keksobooking" method="post" enctype="multipart/form-data" autocomplete="off" target="_blanck">
1) опечатка в blank
2) для форм это свойство не используют (далее вы будете делать preventDefault в обработчике)

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +  //   // ------------------------------ Часть вторая --------------------------------
закомментированный код нужно удалять

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +  const initlPinMainPosition = () => {
опечатка init `l` pin main position

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +  const statusDisabled = (elements) => {
имя функции должно содержать глагол - setStatusDisabled

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +  const statusActive = (elements) => {
глагол

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +  const setupAddress = () => {
глагол

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +  const activationPage = () => {
глагол

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +  const checkRoomNumber = (roomNumber) => {
здесь лучше сделать приведение типов `Number(roomNumber)`

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +    switch (guestNumber) {
приведение типов и проверка что не для гостей

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +        if (!(roomNumber === guestNumber)) {
`!(roomNumber === guestNumber)` правильно оформлять так `roomNumber !== guestNumber`

2020-10-04 15:53 UTC, yulllll commented on js/main.js
> +    let roomNumber = checkRoomNumber(adFormRoomNumber.value);
const

2020-10-05 07:48 UTC, Sainthedgehog1 commented on js/main.js
> +  //   // ------------------------------ Часть вторая --------------------------------
В задании сказано закоментировать

2020-10-05 07:55 UTC, Sainthedgehog1 commented on js/main.js
> +  const checkRoomNumber = (roomNumber) => {
не вижу смысла, тут не явное приведение типов, зачем явное

2020-10-05 08:17 UTC, Sainthedgehog1 commented on js/main.js
> +    switch (guestNumber) {
я же тут только проверяю количество гостей, про приведение типов тоже не понял зачем оно нужно явное, если не явное работает. Или это из той оперы, где нужно доказать арбузу, что он не дыня

2020-10-05 17:07 UTC, merged